//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelMvcProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hakkimizda
    {
        public int id { get; set; }
        public string Baslik { get; set; }
        public string Slogan { get; set; }
        public string Detay { get; set; }
        public string ResimUrl { get; set; }
    }
}
